
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "galooliDevKitService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://galoolitools.dnsalias.com/galooliDevKitService/galooliDevKitService.svc?wsdl")
public class GalooliDevKitService
    extends Service
{

    private final static URL GALOOLIDEVKITSERVICE_WSDL_LOCATION;
    private final static WebServiceException GALOOLIDEVKITSERVICE_EXCEPTION;
    private final static QName GALOOLIDEVKITSERVICE_QNAME = new QName("http://tempuri.org/", "galooliDevKitService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://galoolitools.dnsalias.com/galooliDevKitService/galooliDevKitService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GALOOLIDEVKITSERVICE_WSDL_LOCATION = url;
        GALOOLIDEVKITSERVICE_EXCEPTION = e;
    }

    public GalooliDevKitService() {
        super(__getWsdlLocation(), GALOOLIDEVKITSERVICE_QNAME);
    }

    public GalooliDevKitService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GALOOLIDEVKITSERVICE_QNAME, features);
    }

    public GalooliDevKitService(URL wsdlLocation) {
        super(wsdlLocation, GALOOLIDEVKITSERVICE_QNAME);
    }

    public GalooliDevKitService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GALOOLIDEVKITSERVICE_QNAME, features);
    }

    public GalooliDevKitService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GalooliDevKitService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDevKitService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDevKitService")
    public IDevKitService getBasicHttpBindingIDevKitService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDevKitService"), IDevKitService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDevKitService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDevKitService")
    public IDevKitService getBasicHttpBindingIDevKitService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDevKitService"), IDevKitService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GALOOLIDEVKITSERVICE_EXCEPTION!= null) {
            throw GALOOLIDEVKITSERVICE_EXCEPTION;
        }
        return GALOOLIDEVKITSERVICE_WSDL_LOCATION;
    }

}
